# version: '3.8'

# services:
#   db:
#     image: mysql:5.7
#     container_name: challenge3-db
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#     networks:
#       - challenge3-network

#   node-service:
#     image: node:14
#     container_name: challenge3-node-service
#     environment:
#       - DB_HOST=${DB_HOST}
#       - DB_USER=${DB_USERNAME}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_NAME=${DB_DATABASE}
#       - NODE_ENV=production
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/usr/src/app
#     networks:
#       - challenge3-network
#     command: "npm start"

#   nginx:
#     image: nginx:latest
#     container_name: challenge3-nginx
#     ports:
#       - "8080:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - node-service
#     networks:
#       - challenge3-network

# volumes:
#   db_data:

# networks:
#   challenge3-network:
#     driver: bridge


# docker-compose.yml file
version: '3.8'

services:
  db:
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      # - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network


  node-service:
    build: ./docker/api
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    networks:
      - app-network
    depends_on:
      - db


  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'
    networks:
      - app-network
    depends_on:
      - node-service

volumes:
  db_data:

networks:
  app-network:
    driver: bridge


